services:

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - current
    ports:
      - "5432:5432"
    env_file: .env-docker
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]

  database-migration:
    image: migrate/migrate
    container_name: database-migration
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - current
    volumes:
      - ".:/code"
    env_file: .env-docker
    command: [ "-path", "/code/migrations/", "-database",  "$DATABASE_URL", "up" ]

  redis:
    image: redis:6
    container_name: redis
    restart: unless-stopped
    networks:
      - current
    command: redis-server --save 60 1 --requirepass MDNcVb924a
    ports:
      - '6379:6379'

networks:
  current:
    name: current
